[book]
authors = ["Qhy23"]
description = "计算机网络技术基础实验"
language = "zh-CN"
src = "./src"
title = "计算机网络技术基础实验"

[preprocessor.katex]
after = ["links"]
output = "htmlAndMathml"
pre_render = true

[output.html]
additional-css = ["css/fontsize.css"]
git-repository-url = "https://github.com/Qhy23/mdbook"

[output.html.search]
boost-hierarchy = 2
boost-paragraph = 1
boost-title = 2
expand = true
heading-split-level = 2
limit-results = 20
use-boolean-and = true